version: "3"
services:
  react-app:
    image: react-app-dev
    build: ./web-client/
    stdin_open: true
    ports:
      - "3002:3002"
    networks:
      - mern-app
    volumes:
      - ./web-client/:/usr/src/app
      - /usr/src/app/node_modules
  api-server:
    image: api-server
    env_file: ./api/config/dev.env
    ports:
      - "5000:5000"
    networks:
      - mern-app
    volumes:
      - ./api/:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - mern-app
    volumes:
      - mongo-data:/data/db
networks:
  mern-app:
    driver: bridge
volumes:
  mongo-data:
    driver: local
